### ISSUE TITLE
metric collection error

### ISSUE THREAD

**Issue by callMe-Root** [camptocamp/ipahealthcheck_exporter#9] opened 2023-02-02 11:53 UTC
Hi, after I run  `ipa-healthcheck --failures-only > /var/log/ipa/healthcheck/healthcheck.log` commmand, collector starts to give errors, but without it I can't get replication and other ldap related problems:

`collected metric "ipa_replication_check" { label:<name:"ipahealthcheck" value:"ReplicationCheck" > gauge:<value:0 > } was collected before with the same name and label values`

![resim](https://user-images.githubusercontent.com/68336965/216316811-52f9a2b6-afe5-452d-84f1-044fbdf408f6.png)

![resim](https://user-images.githubusercontent.com/68336965/216317421-c586dd9b-8c2c-41e9-9306-5ac290b81bc4.png)

**Comment by lconsuegra** [comment] 2023-05-26 14:02
Hello, are you still having the issue ? 

If so can you tell me which version of freeipa / ipa-healthcheck and the exporter you are running so I can try to reproduce ? 

Thanks.

**Comment by taniahagan** [comment] 2023-06-27 15:03
Hi, 

Hope you don't mind me replying to this thread.  I am also having this issue.  I have tried with ipahealthcheck_exporter-0.0.14-rc7.linux-amd64 and ipahealthcheck_exporter-0.0.13.linux-amd64.tar.gz.  Currently using ipa VERSION: 4.9.10, API_VERSION: 2.251.  I will be upgrading (hopefully) to ipa version 4.9.11 on Friday.  

If I restart ipa-healthcheck and then ipahealthcheck_exporter it fixes it temporary before returning again. 

I'd like to see this issue resolved to improve the monitoring so any tips would be most welcome. 

Many Thanks, 
Tania

**Comment by diogenxs** [comment] 2023-09-07 13:29
I have the same error; it happens that sometimes there are different "errors" for the same check

`cat /var/log/ipa/healthcheck/healthcheck.log | jq '.[] | select(.check=="ReplicationCheck")'`
```json
{  
 "source": "ipahealthcheck.ds.replication",  
 "check": "ReplicationCheck",  
 "result": "CRITICAL",  
 "uuid": "52fd75c9-b748-4dd3-908d-289a92987d06",  
 "when": "20230907121320Z",  
 "duration": "7.024863",  
 "kw": {  
   "key": "DSREPLLE0001",  
   "items": [  
     "Replication",  
     "Agreement"  
   ],  
   "msg": "The replication agreement (ipa-2.ipa.example.com-to-ipa-1.ipa.example.com) under \"dc=ipa,dc=example,dc=com\" is not in synchronization."  
 }  
},  
{  
 "source": "ipahealthcheck.ds.replication",  
 "check": "ReplicationCheck",  
 "result": "ERROR",  
 "uuid": "c93129b9-f493-4aeb-9f87-2869a34e2ee6",  
 "when": "20230907121321Z",  
 "duration": "7.024885",  
 "kw": {  
   "key": "DSREPLLE0003",  
   "items": [  
     "Replication",  
     "Agreement"  
   ],  
   "msg": "The replication agreement (metoipa-3.ipa.example.com) under \"dc=ipa,dc=example,dc=com\" is not in synchronization.\nStatus message: error (1) can't acquire busy replica (unable to acquire replica: the replica is currently being updated by another supplier.)"  
 }  
}  
```
so, when looping through the JSON the exporter fails as it is adding the metric with the same name and labels?
https://github.com/camptocamp/ipahealthcheck_exporter/blob/master/ipahealthcheck_exporter.go#L157-L182


I'm running `ipa-server-4.9.6`  and `ipa-healthcheck-0.7-6`, which is kinda old, I'll try to upgrade it

**Comment by lconsuegra** [comment] 2023-11-08 13:14
Hello everyone,

> I have the same error; it happens that sometimes there are different "errors" for the same check
> 
> `cat /var/log/ipa/healthcheck/healthcheck.log | jq '.[] | select(.check=="ReplicationCheck")'`
> 
> ```json
> ...
> ```
> 
> so, when looping through the JSON the exporter fails as it is adding the metric with the same name and labels? https://github.com/camptocamp/ipahealthcheck_exporter/blob/master/ipahealthcheck_exporter.go#L157-L182
> 
> I'm running `ipa-server-4.9.6` and `ipa-healthcheck-0.7-6`, which is kinda old, I'll try to upgrade it

@diogenxs Yes its exactly that, thanks for the investigation. I added "result" as a new label to differentiate the ReplicationCheck checks. I hope the case same check same severity never happen or I will have to add also the "key".

@callMe-Root @taniahagan 
I made a new release with the new label : https://github.com/camptocamp/ipahealthcheck_exporter/releases/tag/v0.0.16-rc1 can you test if that fixes the problem ?

Regards.

**Comment by taniahagan** [comment] 2023-11-22 16:14
I've just copied over the new version and restarted the service and keep seeing: 

An error has occurred while serving metrics:

collected metric "ipa_replication_check" { label:<name:"ipahealthcheck" value:"ReplicationCheck" > label:<name:"result" value:"error" > gauge:<value:0 > } was collected before with the same name and label values

I recreated the ipa-healthcheck log just in case seeing old results, and restarted the service, but still seeing the same result

**Comment by taniahagan** [comment] 2023-11-23 15:39
This is what's in my ipa-healthcheck.log

 {
    "source": "ipahealthcheck.ds.replication",
    "check": "ReplicationCheck",
    "result": "ERROR",
    "uuid": "fe6c5ad5-5712-46b2-907c-c0a3d89e6f79",
    "when": "20231123040009Z",
    "duration": "1.728195",
    "kw": {
      "key": "DSREPLLE0005",
      "items": [
        "Replication",
        "Agreement"
      ],
      "msg": "The replication agreement (X) under \"dc=X,dc=X\" is not in synchronization,\nbecause the consumer server is not reachable."
    }
  },
  {
    "source": "ipahealthcheck.ds.replication",
    "check": "ReplicationCheck",
    "result": "ERROR",
    "uuid": "c921a01a-172a-4921-9054-d773623458c4",
    "when": "20231123040010Z",
    "duration": "1.728226",
    "kw": {
      "key": "DSREPLLE0005",
      "items": [
        "Replication",
        "Agreement"
      ],
      "msg": "The replication agreement (X) under \"o=X\" is not in synchronization,\nbecause the consumer server is not reachable."
    }

**Comment by taniahagan** [comment] 2023-11-23 16:36
If I modify and add the ipaCheck Uuid this appears to solve it, then adding the different ReplicationCheck results to the metrics, just not sure if this is the best approach.  Any advice?

**Comment by lconsuegra** [comment] 2023-12-05 11:22
Hello,

I was able to reproduce the problem, using uuid is not a good approach since it could lead to a large number of metrics. I added a custom case to manage this check (and use the error msg as a label to differentiate the metrics) 

A new pre release that should fix it for good is available : https://github.com/camptocamp/ipahealthcheck_exporter/releases/tag/v0.0.16-rc2

Can you test please ?.

Regards.

**Comment by lconsuegra** [comment] 2024-02-29 08:05
Hello,

This should be fixed by https://github.com/camptocamp/ipahealthcheck_exporter/releases/tag/v0.0.16.

**Closed by lconsuegra** 2024-02-29 08:05 UTC
